SRCS := public/const_def.f90 public/const_lib.f90
SRCS_CHECK := test/src/test_const.f
MODULE_NAME := const
MODULES := const_def.mod const_lib.mod
BINTYPE := static-lib

MAKEFLAGS += -I../make

include ../make/Makefile
