#!/usr/bin/env perl
use strict;
use warnings "all";
use File::Basename;

my $build_dir = $ENV{'BUILD_DIR'};
my $install_includes = $ENV{'INSTALL_INCLUDES'};
my $modules = $ENV{'MODULES'};

while (my $line = <>) {
    if ($line =~ /([^ ]*) (.*): ([^ ]*) (.*)/) {
        my ($obj, $mods, $src, $dep_mods) = ($1, $2, $3, $4);
        $obj =~ s{$build_dir/$build_dir}{$build_dir};
        my $obj_dir = dirname($obj);
        my $obj_fname = basename($obj);
        my $compiler = "FCOMPILE";

        if ($src =~ /(.*).f$/) {
            $compiler = "FCOMPILE_LEGACY";
        }

        print <<~"MAKEFILE"
        $obj.anc : $src $dep_mods | \$(MODULE_DIR)/ $obj_dir/
        \t\@touch \$@
        \t\$(FCOMPILE_MODULE) $src -J \$(MODULE_DIR)
        $mods : $obj.anc
        $obj : $src $dep_mods | \$(SCRATCH_DIR)/ $obj_dir/
        \t\@rm -rf \$(SCRATCH_DIR)/$obj_fname/
        \t\@mkdir \$(SCRATCH_DIR)/$obj_fname/
        \t\$($compiler) $src -o $obj -I \$(MODULE_DIR) -J \$(SCRATCH_DIR)/$obj_fname/
        \t\@rm -rf \$(SCRATCH_DIR)/$obj_fname/
        MAKEFILE
    }
}

foreach my $f (split " ","$install_includes $modules") {
    my $basename_f = basename($f);
    print <<~"MAKEFILE"
    $build_dir/include/$basename_f : $f | $build_dir/include/
    \tcp \$^ \$@
    MAKEFILE
}
